baseurl: "http://docs.shouldbee.io"
title: ShouldBeeドキュメント
permalinks:
  post: /:year/:month/:title/
params:
  Description: null
  Copyright: ©ShouldBee 2014 - 2016. All rights reserved.
MetaDataFormat: yaml
